<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Athena.Core\Athena.Core.csproj" />
    <ProjectReference Include="..\Athena.Plugins\Athena.Plugins.csproj" />
    <ProjectReference Include="..\Athena.Filters\Athena.Filters.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.InMemory" />
  </ItemGroup>

</Project>
